version: '3'  
services:
  web:
    image: nginx:latest
    ports:
     - "8080:80"
    links:
     - php
  php:
    image: php:7-fpm
  minion:
    image: salt-minion
    links:
      - "master:salt-master"
    depends_on:
      - master
  master:
    image: salt-master
